// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ParkingLot.Shared.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ParkingLot.Server.Data
{
    public partial interface IParkingLotContextProcedures
    {
        Task<int> DeleteCarBrandsAsync(int? idCarBrand, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteCarTypesAsync(int? idCarType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SelectCarsResult>> SelectCarsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SelectCarsInParkingLotResult>> SelectCarsInParkingLotAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
