// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParkingLot.Shared.Models
{
    public partial class Car
    {
        public Car()
        {
            Entries = new HashSet<Entry>();
            Exits = new HashSet<Exit>();
        }

        public int IdCar { get; set; }
        public int IdCarBrand { get; set; }
        public int IdCarType { get; set; }
        public string RegistrationNumber { get; set; }

        public virtual CarBrand IdCarBrandNavigation { get; set; }
        public virtual CarType IdCarTypeNavigation { get; set; }
        public virtual ICollection<Entry> Entries { get; set; }
        public virtual ICollection<Exit> Exits { get; set; }
    }
}