// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParkingLot.Shared.Models
{
    public partial class CarBrand
    {
        public CarBrand()
        {
            Cars = new HashSet<Car>();
        }

        public int IdCarBrand { get; set; }
        public string BrandName { get; set; }

        public virtual ICollection<Car> Cars { get; set; }
    }
}