// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParkingLot.Shared.Models
{
    public partial class CarType
    {
        public CarType()
        {
            Cars = new HashSet<Car>();
        }

        public int IdCarType { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<Car> Cars { get; set; }
    }
}