// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParkingLot.Shared.Models
{
    public partial class Exit
    {
        public int IdExit { get; set; }
        public int IdExitGate { get; set; }
        public int IdCar { get; set; }
        public DateTime ExitDate { get; set; }
        public int TicketNumber { get; set; }

        public virtual Car IdCarNavigation { get; set; }
        public virtual Gate IdExitGateNavigation { get; set; }
    }
}