// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParkingLot.Shared.Models
{
    public partial class Gate
    {
        public Gate()
        {
            Entries = new HashSet<Entry>();
            Exits = new HashSet<Exit>();
        }

        public int IdGate { get; set; }
        public int GateNumber { get; set; }

        public virtual ICollection<Entry> Entries { get; set; }
        public virtual ICollection<Exit> Exits { get; set; }
    }
}