// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ParkingLot.Shared.Models
{
    public partial class SelectCarsResult
    {
        public int IdCar { get; set; }
        public string BrandName { get; set; }
        public string TypeName { get; set; }
        public string RegistrationNumber { get; set; }
    }
}
